# DO NOT CHANGE THESE
# Changing these options might case problems.
# All Options that are safly changable are documented in each roll 
# or already part of the host_vars/localhost folder.

base_distro: "Arch"

home_path: "{{ ansible_env.HOME }}"
font_path: "{{ home_path }}/.local/share/fonts"