- name: Install Programms
  hosts: local
  gather_facts: yes
  gather_subset: [hardware]
  vars_files:
    - config/config.yml
  tasks:
  
    - name: ansible distrobution
      debug:  
        var: ansible_distribution


    - name: host vars
      debug:  
        var: hostvars
