- name: Install Java 11 jdk
  become: true
  package: 
    name: "{{ jdk }}"
    state: present
  when: jdk is defined

- name: Install Java 11 jre
  become: true
  package: 
    name: "{{ jre }}"
    state: present
  when: jre is defined

- name: Install Java 11 Doc
  become: true
  package: 
    name: "{{ doc }}"
    state: present
  when: doc is defined
